### ISSUE TITLE
Guess adsorbate positions from calculations on same slab/position with similar DFT settings

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#14]
If we want to add a configuration (say CO on a Cu111 hollow site) w/ PBE and we already have a calculation for the same site w/ beef-vdw, then we could save a lot of calculation time by starting from the PBE configuration.

This would involve some way of adjusting the unit cells, or perhaps moving the adsorbate the same relative amount to the 'adsorption site'

**Comment by ktran9891** [comment]
It doesn't seem like we will be using BEEF anytime soon. Let's just revive this issue if we ever actually start doing this.
