### ISSUE TITLE
Include information from initial state when moving

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#16]
If a relaxation moves from an initial (guessed) site to a more stable site, we (probably) know that the first is high energy than the second, even if we don't know exactly how much higher it is.  

We should find a way to incorporate this information into estimates for the lowest energy configuration on a surface

**Comment by ktran9891** [comment]
I'm not sure what this means anymore. I'll close it later unless you remember what this is talking about and deem it worthy of keeping, @zulissi.

**Comment by zulissi** [comment]
This is related to something Pari has been thinking about

**Comment by ktran9891** [comment]
I'm still not clear on the specifics of what we'd do with this information. Is this more of a data-analysis thing? If so, it might belong somewhere else, not as a GASpy issue.

**Comment by ktran9891** [comment]
Over two years with no progress on this. It probably isn't a priority for us. Closing for now. We can reopen if we want to.
