### ISSUE TITLE
Setup Google login for access to live GASdb

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#22]
We should have publicly available/open data sets on the website (snapshots of GASdb that we're confident of the data for, and published), but the current one changes frequently and can contain mistakes.  

It would be great to have a google login required for access to the database to get a sense for who's using it/etc.  Something like this: https://pythonspot.com/en/login-to-flask-app-with-google/

**Comment by ktran9891** [comment]
We recently [added](https://github.com/ulissigroup/GASpy_manuscript/commit/c88d96eb0defd2053f17a2686d6593871fb2b5fa) a cache of our data to the [GASpy_manuscript](https://github.com/ulissigroup/GASpy_manuscript) repo. Still working on a live version.

**Comment by ktran9891** [comment]
Addresse [here](https://ulissigroup.cheme.cmu.edu/software-data/).
