### ISSUE TITLE
insufficient bands in vasp

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#23]
Some of the calculations are failing due to not enough empty bands.  Example calculation on arjuna:

4:44] 
http://gilgamesh.cheme.cmu.edu:5000/id/14185

[4:45] 
`/home/zulissi/fireworks/block_2017-06-09-14-24-44-768845/launcher_2017-06-09-15-55-49-468712`

[4:45] 
`/home/zulissi/fireworks/block_2017-06-09-07-10-03-245689/launcher_2017-06-09-11-30-48-816060`

[4:45] 
(blank and adsorbed H runs)

**Comment by ktran9891** [comment]
Closing for staleness. Can reopen if needed.
