### ISSUE TITLE
Store information about previous steps at each level for FireWorks

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#26]
For example, the FW for the a Ag(100) surface should contain information about the bulk FW that it is based on.  Likewise, CO on an Ag(100) surface should probably contain the FW for the slab and for the bulk that it is based on.  

This would make a verifiable chain of links, and allow everything based on a known (wrong) structure to be cleared at the same time.  

Implementation could be by adding more things to the "name" field of each firework that gets submitted.

**Comment by ktran9891** [comment]
Surface energy collection now has fwids (https://github.com/ulissigroup/GASpy/commit/13fe82627dec74bde1b18725f9a670112981d736) and so does adsorption collection (https://github.com/ulissigroup/GASpy/commit/8a24ae5223586c8c4d78b233f6df6b12e53236cd).

**Comment by ktran9891** [comment]
Update:  I forgot that (https://github.com/ulissigroup/GASpy/commit/790599f37fbf1843e24eeafff861dd3696633178) reverted the addition of bulk FWID to surface energy collection. We will be keeping it this way.
