### ISSUE TITLE
Frequent failures in relaxations

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#39]
Approximately 10% of relaxations are fizzling at the moment.  Upon closer inspection, most of these are caused by symmetry and kpoint problems. For example, FW142082: /home/zulissi/fireworks/block_2017-12-01-07-49-08-149319/launcher_2017-12-01-20-01-25-168907 fails.  Small adjustments to the initial conditions don't seem to help.  These fail with things like

>  VERY BAD NEWS! internal error in subroutine IBZKPT:
 Reciprocal lattice and k-lattice belong to different class of lattices. Often results are still useful...     168

Adding SYMPREC=1e-10 seems to fix the issue (affecting how it calculates symmetries). I think the easiest fix is to add this to the default for slab+adsorbate relaxations. Any symmetries it finds are fake/unwanted anyways.

There is a similar error for some slab optimizations, but adding SYMPREC does not seem to solve the problem.  I can get the errors to clear using a different kpoint mesh (for example, gamma instead of k-point), but I'm a little worried that this will lead to problems since the two might give different results. Until we fix this problem, there are some surface that we simply cannot calculate adsorption energies for.

**Comment by ktran9891** [comment]
Our current fizzle rate for adslabs floats between 90–95%. This seems good enough for me. I'll just label this as stale for now and close it. We can reopen if we want to get that number closer to 100%.
