### ISSUE TITLE
max_atoms explicitly set in gaspy.tasks.EnumerateAlloys

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#49]
Enumerating catalog with the new default (max_atoms = 80) will cause duplicate entries into the catalog as it looks like a new enumeration. It has thus been set to the old default at max_atoms = 50.  

After writing the gapsy_manuscript, this default should be removed and the catalog should be regenerated.

**Comment by ktran9891** [comment]
Is this still an issue, @zulissi? I know you've been playing with the catalog a bunch. I'm not sure if this issue still matters in our current state.

**Comment by ktran9891** [comment]
With the new [`gaspy.tasks`](https://github.com/ulissigroup/GASpy/commit/ea03e8357e269d9ddd692e1f59bd400a56957162#diff-a403dd312da66e4b22642b73fe7d7135) infrastructure, we now look for a calculation in FireWorks before submitting it. This FireWorks query does not have `max_atoms` in it, which addresses this issue directly.

[This commit](https://github.com/ulissigroup/GASpy/commit/2ce24be2c0ed46e75dd40f7f8f1789fd4a076c96) also implements the `max_atoms` for bulk calculations as a Luigi argument, so we can still prevent submission of large bulks.
