### ISSUE TITLE
duplicate entries in GASdb due to SCRATCH token removal

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#50]
We store tokens on scratch to indicate that an entry was added to the adsorption database, so after 3 months (or whatever the timescale for scratch removing things) the token is removed and the entry gets put back in to the DB.

Proposed solutions:
1) do nothing, and periodically remove duplicate entries with the new detect_duplicates.py script.
2) periodically touch every DumpToAdsorptionDB token to keep them fresh and prevent removal.

**Comment by ktran9891** [comment]
I made a function to clear out duplicates:  https://github.com/ulissigroup/GASpy/commit/50fb7a6b6d776522a338ffb1a5e4d4ef0c2d3f5f

And added the function to our maintenance script:  https://github.com/ulissigroup/GASpy/blame/software_update/maintenance/clean_up_fw.sh


Admittedly, this is pretty hacky and your 2nd solution seems a lot cleaner.

**Comment by ktran9891** [comment]
Our GASdb updater functions now add things more intelligently, i.e., it simply updates GASdb based on the difference between FireWorks and Mongo.

We also don't use tokens anymore, since our Mongo updating scripts are now simply functions, not `luigi.Task` classes.
