### ISSUE TITLE
atoms rotate update

### ISSUE THREAD

**Issue by zulissi** [ulissigroup/GASpy#61]
Our log files are now dominated by copies of this warning. We should fix the atoms.rotate calls. This will probably require a little linear algebra / thought to make sure it's consistent.

/miniconda3/envs/GASpy_conda/lib/python3.6/site-packages/ase/atoms.py:1216: UserWarning: Please use new API: atoms_obj.rotate(a, v) where v its a vector to rotate around and a is the angle in degrees.
  warnings.warn(warning)

**Comment by ktran9891** [comment]
[This commit](https://github.com/ulissigroup/GASpy/commit/19f80c95f4bc9ca1b2deb972118610eade453e2c) created the `orient_atoms_upwards` function. The syntax didn't really change in the refactored version, but the unit test of the function doesn't show the error anymore. Any we don't see it in the log files, either. Maybe some change in the Docker image fixed the issue?
