### ISSUE TITLE
Fix magnetic moments when making doc from atoms

### ISSUE THREAD

**Issue by ktran9891** [ulissigroup/GASpy#78]
@SeoinBack found that in our `_make_atoms_dict` function, we are not saving the magnetic moments correctly. We should be getting them from the entire atoms object, not each individual atom. If we get it from each individual atom, then the moments calculated during VASP relaxation are effectively lost.

**Comment by SeoinBack** [comment]
fixed.

**Comment by ktran9891** [comment]
Need to test and commit the fix. The change is currently failing.

**Comment by ktran9891** [comment]
Fixed by https://github.com/ulissigroup/GASpy/commit/93a215a8eb5e485dd446e54e1376efddff18314c
