### ISSUE TITLE
Avoid producing electronic log files from the start

### ISSUE THREAD

**Issue by samueldy** [ulissigroup/GASpy#95]
`vasp_functions.py._perform_relaxation` seems to always delete electronic log files (CHG, CHGCAR, WAVECAR) after the relaxation is done. 

https://github.com/ulissigroup/GASpy/blob/6977f75943db7c768260416a735617a8edfaf4c8/gaspy/vasp_functions.py#L318-L327

Writing these files at the end of a relaxation can take a lot of time and might cause a Firework to fizzle due to exceeding a Slurm time limit. As these files seem to always be deleted after relaxation, I think it would be better to specify `dict(lwave=False, lcharg=False)` in `gaspy.defaults`, or merge these settings into `vasp_flags` at runtime.

Thoughts?

**Comment by ktran9891** [comment]
Resolved as per #96
