### ISSUE TITLE
Stop doing VASP queries on lwave and lcharg

### ISSUE THREAD

**Issue by ktran9891** [ulissigroup/GASpy#97]
As per #96 , we added VASP settings to say whether we want to save electronic log files or not. But now all our calculation finding tasks are looking for that VASP flag and not finding it in our historical databases. And since we can't find them, we end up resubmitting calculations where the only difference is whether we save the log files or not.

Let's ignore this flag during queries, similar to [this](https://github.com/ulissigroup/GASpy/blob/master/gaspy/tasks/calculation_finders.py#L366) paragraph.

**Comment by samueldy** [comment]
Sorry about that. Should thought about that.

**Comment by ktran9891** [comment]
Fixed by #99
